namespace INSS.EIIR.Data.Models
{
    public partial class CasesCsv
    {
        public string? CaseNo1 { get; set; }
        public string? InsolvencyType { get; set; }
        public string? Court { get; set; }
        public string? CourtNo { get; set; }
        public string? CaseYear { get; set; }
        public string? BatchType { get; set; }
        public string? BatchNo { get; set; }
        public string? FileNo { get; set; }
        public string? OfficeId { get; set; }
        public string? CaseName { get; set; }
        public string? Partnership { get; set; }
        public string? PetitionDate { get; set; }
        public string? InsolvencyDate { get; set; }
        public string? HtipDate { get; set; }
        public string? CaseStatus { get; set; }
        public string? OnBancs { get; set; }
        public string? OnLois { get; set; }
        public string? TradeClassNo { get; set; }
        public string? TradingStartDate { get; set; }
        public string? TradingEndDate { get; set; }
        public string? MembersApptDate { get; set; }
        public string? GazetteDate { get; set; }
        public string? UserId { get; set; }
        public string? ExaminerId { get; set; }
        public string? AnnulmentType { get; set; }
        public string? AnnulmentDate { get; set; }
        public string? StayFlag { get; set; }
        public string? StayExpiryDate { get; set; }
        public string? PreRegisterFlag { get; set; }
        public string? FinalReleaseDate { get; set; }
        public string? OnEms { get; set; }
        public string? IsedCaseId { get; set; }
        public string? IscisCaseRef { get; set; }
        public string? CreatedDate1 { get; set; }
        public string? CascasedetailLastUpdatedDate1 { get; set; }
        public string? CasbankruptcasedetailLastUpdatedDate1 { get; set; }
        public string? PtycourtLastUpdatedDate1 { get; set; }
        public string? CdscasedatastoreLastUpdatedDate1 { get; set; }
        public string? CascasehearingLastUpdatedDate1 { get; set; }
        public string? PtyofficeLastUpdatedDate { get; set; }
        public string? CaseNo { get; set; }
        public string? IndivNo { get; set; }
        public string? IndivType { get; set; }
        public string? Title { get; set; }
        public string? Initials { get; set; }
        public string? Surname { get; set; }
        public string? Forenames { get; set; }
        public string? AddressLine1 { get; set; }
        public string? AddressLine2 { get; set; }
        public string? AddressLine3 { get; set; }
        public string? AddressLine4 { get; set; }
        public string? AddressLine5 { get; set; }
        public string? Postcode { get; set; }
        public string? Phone { get; set; }
        public string? DateOfBirth { get; set; }
        public string? JobTitle { get; set; }
        public string? Sex { get; set; }
        public string? NiNumber { get; set; }
        public string? DeceasedDate { get; set; }
        public string? AddressType { get; set; }
        public string? SummaryCertFlag { get; set; }
        public string? RegisterExpiryDate { get; set; }
        public string? RegisterLastAmendBy { get; set; }
        public string? RegisterLastAmendDate { get; set; }
        public string? AddressWithheldFlag { get; set; }
        public string? IsedIndividualId { get; set; }
        public string? DtSubjectAnnulled { get; set; }
        public string? SubjAnnulmentType { get; set; }
        public string? CreatedDate { get; set; }
        public string? CascasedetailLastUpdatedDate { get; set; }
        public string? CasbktcasedetailLastUpdatedDate { get; set; }
        public string? PtypersonLastUpdatedDate { get; set; }
        public string? PtylocationLastUpdatedDate { get; set; }
        public string? PtypartylocationLastUpdatedDate { get; set; }
        public string? CascasehearingLastUpdatedDate { get; set; }
    }
}
