trigger:
- develop
  
pool:
  vmImage: windows-latest

variables:
- name: buildConfiguration
  value: 'Release'

parameters: 
- name: deployWebapp    
  type: boolean    
  default: true
- name: deployfuncapp    
  type: boolean    
  default: true
- name: deployDailyExtract   
  type: boolean    
  default: true
- name: RunIntTest    
  type: boolean    
  default: true

resources:
  repositories:
  - repository: inss-devops-common-lib
    type: github
    endpoint: InsolvencyService
    name: InsolvencyService/inss-devops-common-lib
    ref: develop
    
stages:
- stage: BuildTest
  displayName: 'Build and Test'
  jobs:  
    - job: 
      steps:
      - task: UseDotNet@2
        inputs:
          version: '6.0.x'

      - task: DotNetCoreCLI@2
        displayName: NuGet Restore
        inputs:
          command: 'restore'
          projects: |
            **/INSS.EIIR*.csproj
            !**/INSS.EIIR*Tests.csproj
  
      - task: Npm@1
        inputs:
          command: 'ci' 
          workingDir: $(System.DefaultWorkingDirectory)/INSS.EIIR.WEB

      - task: DotNetCoreCLI@2
        displayName: 'Build Solution'
        inputs:
          command: 'build'
          # projects: '**/INSS.EIIR*.csproj'
          projects: |
            **/INSS.EIIR*.csproj
            !**/INSS.EIIR*Tests.csproj
          arguments: '--configuration $(buildConfiguration)'
        env:
          MSBUILDSINGLELOADCONTEXT: '1'       

#      - task: DotNetCoreCLI@2
#        displayName: 'Run Tests'
#        inputs:
#          command: test
#          projects: '**/*Tests/*.csproj'
#          arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
#        env:
#            ASPNETCORE_ENVIRONMENT: 'Dev'

      - task: DotNetCoreCLI@2
        displayName: 'Publish Project'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: |
            **/INSS.EIIR*.csproj
            !**/INSS.EIIR*Tests.csproj
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        env:
          MSBUILDSINGLELOADCONTEXT: '1' 
        
      - task: PublishPipelineArtifact@1
        displayName: 'Publish Artifact'
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)' 
          artifactName: 'INSS.EIIR'
        condition: succeeded()

- stage: DeployDev
  displayName: 'Deploy to Dev'
  condition: succeeded()
  variables:
    - group: EIIR-Dev
  jobs:
    - template: deploy-jobs-template.yml
      parameters:
        environment: 'Dev'
        azureSubscription: 'AppServicesDevOps-NonProd'
        deployWebapp: ${{ parameters.deployWebapp }}
        deployfuncapp: ${{ parameters.deployfuncapp }}
        deployDailyExtract: ${{ parameters.deployDailyExtract }}

- stage: DeploySit
  displayName: 'Deploy to Sit'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
  variables:
    - group: EIIR-Sit
  jobs:
    - template: deploy-jobs-template.yml
      parameters:
        environment: 'Sit'
        azureSubscription: 'AppServicesDevOps-NonProd'
        deployWebapp: ${{ parameters.deployWebapp }}
        deployfuncapp: ${{ parameters.deployfuncapp }}
        deployDailyExtract: ${{ parameters.deployDailyExtract }}

- stage: DeployPreProd
  displayName: 'Deploy to PreProd'
  condition: and(succeeded(), contains(variables['build.sourceBranch'], 'refs/heads/release/'))
  variables:
    - group: EIIR-PreProd
  jobs:
    - template: deploy-jobs-template.yml
      parameters:
        environment: 'PreProd'
        azureSubscription: 'AppServicesDevOps-NonProd'
        deployWebapp: ${{ parameters.deployWebapp }}
        deployfuncapp: ${{ parameters.deployfuncapp }}
        deployDailyExtract: ${{ parameters.deployDailyExtract }}

- stage: DeployProd
  displayName: 'Deploy to Prod'
  condition: and(succeeded(), contains(variables['build.sourceBranch'], 'refs/heads/release/'))
  variables:
    - group: EIIR-Prod
  jobs:
    - template: deploy-jobs-template.yml
      parameters:
        environment: 'Prod'
        azureSubscription: 'AppServicesDevOps-Prod'
        deployWebapp: ${{ parameters.deployWebapp }}
        deployfuncapp: ${{ parameters.deployfuncapp }}
        deployDailyExtract: ${{ parameters.deployDailyExtract }}






